name: CI

#Execute on master pull and any pull request

on: 
  push:
    branches: master
  pull_request:
    branches: '*'
 
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Package restore
      run: dotnet restore
    - name: Execute tests
      run: dotnet test
