name: CI

on: [push, pull_request]
 
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Package restore
      run: dotnet restore
    - name: Execute tests
      run: dotnet test
